### ISSUE TITLE
Config page always crashing

### ISSUE THREAD

**Issue by dummysky366** [derivat3/pebble-watchface-agile-cockpit#1]
Device: Galaxy S8, Android 9
Watch: Pebble Time
Config page constantly crashes. Running latest Pebble APK.

**Comment by dummysky366** [comment]
Just heard about why.

**Comment by derivat3** [comment]
Thank you for the bug report. 
The watchface detects a system crash and offers a limited version the second time you try to open the settings menu.
Even if I cannot fix the problem, I will point out this fallback solution in the next version.

This fallback solution was introduced with version 1.3 and successfully tested with ...
Nexus 4 / Android 5.1.1
Honor 5X / Android 6.0.1
