### ISSUE TITLE
Setting screen too big

### ISSUE THREAD

**Issue by Alexmakes** [derivat3/pebble-watchface-agile-cockpit#6]
Every time load up the config menu after following the instructions on the minimised menu it crashes and shows a bug report
Happens on both Moto g6 latest apk and the modded apk pts. Android pie

**Comment by derivat3** [comment]
Hi, thanks for the report. I am currently working on a solution to this problem. In the best case this is solved with version 2.3.

**Comment by derivat3** [comment]
Hi,
unfortunately it took a little longer than originally assumed. But with version 3.0 there is now also a fully comprehensive online settings menu. I very much hope this solves your problem now.
Best regards, sesio
