### ISSUE TITLE
Keeps falling back to reduced settings

### ISSUE THREAD

**Issue by f8lxninja** [derivat3/pebble-watchface-agile-cockpit#8]
It appears that the normal settings is bugged because when I try to disable the switch at the top and follow the instructions, it crashes the next time I try to open the settings. It shows a black screen and then kicks me out to the watchface menu and says that the pebble disconnected.

**Comment by derivat3** [comment]
Thank you for this report. Unfortunately your phone cannot handle the config size which result in this minimized fallback solution. I try to solve this problem in this feature request ... #6

**Comment by f8lxninja** [comment]
I did see that, although with me it crashes/freezes the pebble app instead of showing me a bug report.

**Comment by derivat3** [comment]
Hi, 
unfortunately it took a little longer than originally assumed. But with version 3.0 there is now also a fully comprehensive online settings menu. I very much hope this solves your problem now.
Best regards, sesio
