### ISSUE TITLE
(iOS) Pebble App Settings Not Loading

### ISSUE THREAD

**Issue by lmoussa** [derivat3/pebble-watchface-agile-cockpit#9]
Hey! I just downloaded this watchface and I love the concept! Unfortunately, I can’t get past the loading screen after opening its settings. It’s not an internet issue as far as I can tell, as when I turned my wifi off it didn’t give me the “check your internet” prompt that I get from other watchfaces. I haven’t touched code in forever so I don’t really know what I’m talking about, but I saw that you are one of the few people still updating their pebble apps! I figured this was worth reporting, and I can provide more info if needed!
Thank you!

**Comment by derivat3** [comment]
Hi lmoussa,
thanks for the report. Having only developed on Android, I was blind to the limitations of older iOS versions. I will now analyze it and try to fix it.

**Comment by derivat3** [comment]
Hi lmoussa, 
I updated the watchface to v4.2 which should now solve many iOS related issues. I've tested the Watchface with an iPhone 6 ... successfully so far. Unfortunately the screenshot feature is not supported with iOS 15... maybe newer OS versions can handle Canvas in headless mode.
